services:

  broker:
    image: rabbitmq:3
    container_name: broker
    ports:
      - 5672:5672

  app:
    container_name: app
    build:
      context: .
      target: api
    volumes:
      - ./src:/app/

  service:
    container_name: service
    build:
      context: .
      target: service
    depends_on:
      - broker
    volumes:
      - ./example_service:/app/

networks:
  default:
    external: true
    name: msets_default
